// mock模拟数据
import Mock from 'mockjs'

// 图表数据
let list = []
export default{
    getStatisticalData:()=>{
        // Mock.Random.float产生随机数100到8000之间 保留小数 最小0位,最大0位
        for(let i = 0; i < 7; i++){
            list.push(
                Mock.mock({
                    苹果:Mock.Random.float(100,8000,0,0),
                    vivo:Mock.Random.float(100,8000,0,0),
                    oppo:Mock.Random.float(100,8000,0,0),
                    魅族:Mock.Random.float(100,8000,0,0),
                    三星:Mock.Random.float(100,8000,0,0),
                    小米:Mock.Random.float(100,8000,0,0),
                })
            )
        }
        return {
            code:20000,
            data:{
                // 饼图
                videoData:[
                    {
                        name:'小米',
                        value:2999
                    },
                    {
                        name:'苹果',
                        value:5999
                    },
                    {
                        name:'vivo',
                        value:1999
                    },
                    {
                        name:'oppo',
                        value:3999
                    },
                    {
                        name:'魅族',
                        value:999
                    },
                    {
                        name:'三星',
                        value:3999
                    },
                ],
                // 柱状图
                userData:[
                    {
                        date:'周一',
                        new:50,
                        active:200
                    },
                    {
                        date:'周二',
                        new:100,
                        active:500
                    },
                    {
                        date:'周三',
                        new:90,
                        active:300
                    },
                    {
                        date:'周四',
                        new:10,
                        active:100
                    },
                    {
                        date:'周五',
                        new:85,
                        active:300
                    },
                    {
                        date:'周六',
                        new:27,
                        active:254
                    },
                    {
                        date:'周日',
                        new:66,
                        active:155
                    },
                ],
                // 折线图
                orderData:{
                    date:['20191001','20191002','20191003','20191004','20191005','20191006','20191007'],
                    data:list
                },
                tableData:[
                    {
                        name:'oppo',
                        todayBuy:200,
                        monthBuy:300,
                        totalBuy:1800
                    },
                    {
                        name:'vivo',
                        todayBuy:150,
                        monthBuy:200,
                        totalBuy:1000
                    },
                    {
                        name:'苹果',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800
                    },
                    {
                        name:'小米',
                        todayBuy:100,
                        monthBuy:30,
                        totalBuy:480
                    },
                    {
                        name:'三星',
                        todayBuy:10,
                        monthBuy:300,
                        totalBuy:500
                    },
                    {
                        name:'魅族',
                        todayBuy:120,
                        monthBuy:400,
                        totalBuy:850
                    },
                    {
                        name:'华为',
                        todayBuy:100,
                        monthBuy:3000,
                        totalBuy:8000
                    },
                    {
                        name:'红米',
                        todayBuy:200,
                        monthBuy:300,
                        totalBuy:700
                    },
                    {
                        name:'中兴',
                        todayBuy:80,
                        monthBuy:300,
                        totalBuy:600
                    },
                ]
            }
        }
    }
}